services:
  redis:
    image: "redis:alpine"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    container_name: redis
    command: "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    expose:
      - 6379
